# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SWXMLHash', '~> 2.1.0'
pod 'SwiftSpinner'
pod 'PullToRefresher', '~> 1.0'
pod 'Alamofire', '~> 3.3'

target 'bitcamp2016' do

end

target 'bitcamp2016Tests' do

end

target 'bitcamp2016UITests' do

end

