# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'bitcamp2016' do

end

target 'bitcamp2016Tests' do

end

target 'bitcamp2016UITests' do

end

